openapi: 3.0.3
info:
  title: Superheros API
  description: API for CRUD operations on superheros
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /v1/superheros/:
    get:
      tags:
        - superhero
      summary: Retrieve all superheros
      operationId: getSuperheros
      responses:
        '200':
          description: A list of superheros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Superhero'
    post:
      tags:
        - superhero
      summary: Create a superhero
      operationId: createSuperhero
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Superhero'
      responses:
        '201':
          description: The created superhero
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Superhero'
  /v1/superheros/{id}:
    get:
      tags:
        - superhero
      summary: Retrieve a superhero by ID
      operationId: getSuperheroById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The requested superhero
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Superhero'
    put:
      tags:
        - superhero
      summary: Update a superhero
      operationId: updateSuperhero
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Superhero'
      responses:
        '200':
          description: The updated superhero
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Superhero'
    delete:
      tags:
        - superhero
      summary: Delete a superhero
      operationId: deleteSuperhero
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Superhero deleted successfully
  /v1/superheros/find:
    get:
      tags:
        - superhero
      summary: Find superheros by name
      operationId: findSuperheros
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of superheros matching the search query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Superhero'
components:
  schemas:
    Superhero:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Superman"